### ISSUE TITLE
Add option for getting more verbose output

### ISSUE THREAD

**Issue by jonhoo** [staticland/staticland#5]
`staticland` is currently very non-verbose, even in the case of errors:

```console
$ staticland deploy --path _site/ --domain example.com --server api.static.land

  null
  
  
```

It would be nice to have `--verbose` and/or `--debug` flag to pass to help diagnose these kinds of issues.

**Comment by sethvincent** [comment]
Yes! Better error messages may be the highest priority thing to improve right now.

**Comment by jonhoo** [comment]
Yeah, I still can't figure out what's wrong with the deployment I'm currently trying to do... :/

**Comment by sethvincent** [comment]
Dang! I'm around and happy to help troubleshoot. I just set up a gitter room for staticland for troubleshooting and such: https://gitter.im/staticland/staticland

**Comment by sethvincent** [comment]
I've fixed a couple bugs in the staticland-api server so things _should_ be ready to try again.

It had a couple typos from switching from a site having one owner to being able to add multiple owners to a site that caused deploys to fail.

**Comment by jonhoo** [comment]
Unfortunately no luck. I still get `null`, though the time before I get `null` is now slightly longer :p

**Comment by sethvincent** [comment]
OK, I'm glad we got that sorted in chat yesterday!

I've gone through the cli tool and made sure that error messages are now saying something meaningful instead of spitting out `null`. 😬 

That's published in v3.0.0.

This issue ought to stay open though, because there still isn't a way to set the verbosity, which I think would be useful.

**Comment by jonhoo** [comment]
One common occurrence is probably to give a path that doesn't exist (due to a typo or something). Currently, running `deploy` with a non-existent path gives: 
```
$ staticland does-not-exist/ somewhere.static.aldn
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, lstat 'does-not-exist'
```

While this does convey the underlying error, this is probably common enough that a more friendly-looking error message would be a useful addition.

**Comment by sethvincent** [comment]
:+1: Agreed.
